import { build } from "esbuild";
const options = {
  bundle: true,
  target: "es2022",
  logLevel: "info",
  legalComments: "none",
};
if (process.argv.includes("--tests")) {
  await build({
    ...options,
    entryPoints: {
      "topology-domain": "frontend/topology/domain.ts",
      http: "frontend/shared/http.ts",
    },
    outdir: ".build",
    outExtension: { ".js": ".cjs" },
    platform: "node",
    format: "cjs",
  });
} else {
  await build({
    ...options,
    entryPoints: [
      "frontend/app.ts",
      "frontend/topology.ts",
      "frontend/security.ts",
    ],
    outdir: "dashboard/static",
    platform: "browser",
    format: "iife",
    banner: {
      js: "// GENERATED by npm run build. Edit frontend/*.ts, not this file.",
    },
  });
}
